# Generated by Django 6.0.3 on 2026-04-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_country_geolocation_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
    ]
